config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path_names: { sign_in: 'login', sign_out: 'logout',
                           sign_up: 'signup', registration: 'register', unlock: 'unlock',
                           confirmation: 'confirm'}
  root 'home#index'

  resources :files
  get 'files/:user/*name' => 'files#show', constraints: { name: /[^\/]*/ }
  delete 'files/:user/*name' => 'files#destroy', constraints: { name: /[^\/]*/ }

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
  has_many :files

  before_validation do
    self.username = email[/[^@]*/]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session
end

app/controllers/files_controller.rb
require 'mimemagic'

class FilesController < ApplicationController
  before_filter :check_auth

  def check_auth
    authenticate_or_request_with_http_basic do |username,password|
      resource = User.find_by email: username
      if resource.valid_password?(password)
        sign_in :user, resource
      end
    end
  end

  def index
    @items = Item.where user: current_user.id
  end

  def show
    user = params[:user]
    name = params[:name]
    id = params[:id]

    if params.has_key? :download
      send_file Rails.root.join('files').join(user).join(name)
      return
    end

    if user and name
      user_instance = User.find_by username: user
      @item = Item.find_by user_id: user_instance.id, name: name
    else
      @item = Item.find id
    end
  end

  def new
  end

  def create
    file = params[:file][:file]

    name = file.original_filename
    user_path = Rails.root.join('files').join(current_user.username)
    dest = File.expand_path(name, user_path)

    if not params[:replace].empty?
      @item = Item.find_by(name: name)
    elsif File.exists? dest
      duplicates = Item.where('name LIKE ?', name + '%')
      ext = File.extname(name)
      base = File.basename(name, ext) + '(' + duplicates.count.to_s + ')'
      # render plain: base and return
      name = base + ext
      dest = File.expand_path(name, user_path)
    end

    src = file.tempfile.path
    stat = File.stat src

    unless @item
      @item = Item.new
      @item.name = name
      @item.path = dest
      @item.user = current_user
      @item.size = stat.size
      @item.filetype = MimeMagic.by_path src
    end

    dest_parent = File.dirname dest
    unless File.exists? dest_parent
      FileUtils.mkdir dest_parent
    end

    if @item.save and FileUtils.mv src, dest
      if params[:from] == 'pack-client'
        render json: @item and return
      end
      redirect_to file_path(@item)
    else
      if params[:from] == 'pack-client'
        render plain: @item and return
      end
      render :new
    end
  end

  def destroy
    user = params[:user]
    name = params[:name]
    id = params[:id]

    if user and name
      user_instance = User.find_by username: user
      @item = Item.find_by user_id: user_instance.id, name: name
    else
      @item = Item.find id
    end
    @item.destroy
    FileUtils.rm @item.path

    redirect_to files_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/files/index.html.erb
<h2>Your Files</h2>
<%= link_to 'New', { :action => :new }, { :class => 'btn' } %>

<br />

<% if @items.any? %>
<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Action</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td><%= link_to item.name, file_path(item) %></td>
      <td><a href='/files/<%= item.user.username %>/<%= item.name %>?download'><%= item.user.username %>/<%= item.name %></a></td>
      <td><%= link_to 'Delete', file_path(item), { :class => 'delete' } %></td>
    </tr>
  <% end %>
</table>
<% else %>
  <p class='empty'>
    You haven't uploaded any files yet, <%= link_to 'upload one!', action: :new %>.
  </p>
<% end %>

app/views/files/new.html.erb
<%= form_for :file, url: files_path do |f| %>
  <%= f.label :file %>
  <%= f.file_field :file %>

  <br />
  <%= f.submit %>
<% end %>

<% if @file and @file.errors.any?
    @file.errors.full_messages.each do |msg| %>

    <p> <%= msg %> </p>
<% end
end %>

<%= link_to 'Back', files_path %>

app/views/files/show.html.erb
<%= link_to 'Back', files_path, { :class => 'btn' } %>

<h2>File Details</h2>
<table>
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th>Size</th>
    <th>Type</th>
  </tr>
  <tr>
    <td><%= @item.name %></td>
    <td><a href='/files/<%= @item.user.username %>/<%= @item.name %>?download'><%= @item.user.username %>/<%= @item.name %></a></td>
    <td><%= @item.size %></td>
    <td><%= @item.filetype or 'Unknown' %></td>
  </tr>
</table>

<% if @item.filetype and @item.filetype.start_with? 'image' %>
  <h3>Image Preview</h3>
  <img src="/files/<%= @item.user.username %>/<%= @item.name %>?download">
<% end %>

app/views/home/index.html.erb
<h2>Hello!</h2>
<p class='main'>
  <% if current_user %>
    <%= link_to 'Your Files', files_path %>
    <br/>
    <%= link_to 'Account Settings', edit_registration_path(current_user) %>
  <% end %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pack</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag         'application' %>
</head>
<body>
  <%= render 'shared/header' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class='wrapper'>
    <%= yield %>
  </div>

  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<footer>
</footer>

app/views/shared/_header.html.erb
<header>
  <h1><%= link_to 'Pack', root_path %></h1>

  <div class='user'>
    <% if current_user %>
      <%= link_to current_user.username, files_path %>
      <%= link_to 'logout', destroy_user_session_path, { :class => 'delete' } %>
    <% else %>
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>
</header>